export interface EditorialContent {
  title: string;
  description: string;
  path: string;
  intent: string;
  schema: string[];
  internalLinks: string[];
  markdown: string;
  html: string;
}

export const educationContent: Record<string, EditorialContent> = {
  "/on-device-ai-assistant-mac": {
    "title": "On-device AI assistant for Mac",
    "description": "Learn what an on-device AI assistant for Mac should keep local, how permissions and optional cloud paths work, and how Pace connects voice, screen context, actions, and memory.",
    "path": "/on-device-ai-assistant-mac",
    "intent": "category explanation for people seeking a local AI assistant on macOS",
    "schema": [
      "Article",
      "SoftwareApplication",
      "BreadcrumbList"
    ],
    "internalLinks": [
      "/screen-aware-ai-assistant-mac",
      "/private-voice-assistant-mac",
      "/mac-ai-assistant-actions",
      "/on-device-meeting-notes-mac",
      "/privacy",
      "/download",
      "/faq"
    ],
    "markdown": "An on-device AI assistant for Mac processes its core interaction loop on the computer: voice capture, transcription, planning, screen context, actions, memory, and speech. The point is not merely that a model can run locally. The point is that useful assistance can happen without making a remote service the default owner of your microphone, screen, and work history.\n\n## What should stay on the Mac\n\nA credible local mode keeps raw voice, screenshots or accessibility context, conversation state, meeting recordings, and personal journals on the device. Network access should be an explicit feature boundary, not an invisible fallback. The product should show when a request leaves the Mac, which provider receives it, and what local alternative remains.\n\n## What makes an assistant useful\n\nA Mac assistant needs more than chat. It should understand the active application, identify relevant controls, propose an action, request approval for material changes, verify what happened, and remember enough context to help later. It also needs restraint: no silent destructive actions, no surprise background network calls, and clear permissions.\n\n## Pace's model\n\nPace is an Apple Silicon macOS voice and action assistant. In local mode, its planner, screen understanding, speech, retrieval, journals, and meeting synthesis run on the Mac. It can use Apple-native or user-enabled external planner tiers, but off-device paths are explicit, consent-gated, visibly indicated, and recorded in a local privacy audit log. Unattended scheduled work does not silently escalate to the network.\n\nPace can read screen context, execute supported actions through its approval and verification pipeline, teach and run local skills, keep bounded local memory, and capture two-track meeting audio for local transcription and note generation. Individual capabilities have their own permissions and opt-ins; “on-device” does not remove the need for macOS microphone, accessibility, screen, calendar, or other relevant access.\n\n## Who this is for\n\nPace fits people who want a Mac-native assistant with voice, screen context, actions, and memory while keeping local processing as the default. It is not a cross-platform cloud chatbot and does not support Intel Macs.\n\n**CTA:** Download Pace, inspect its privacy model, or continue to the screen-aware and action guides.",
    "html": "<p>An on-device AI assistant for Mac processes its core interaction loop on the computer: voice capture, transcription, planning, screen context, actions, memory, and speech. The point is not merely that a model can run locally. The point is that useful assistance can happen without making a remote service the default owner of your microphone, screen, and work history.</p>\n<h2>What should stay on the Mac</h2>\n<p>A credible local mode keeps raw voice, screenshots or accessibility context, conversation state, meeting recordings, and personal journals on the device. Network access should be an explicit feature boundary, not an invisible fallback. The product should show when a request leaves the Mac, which provider receives it, and what local alternative remains.</p>\n<h2>What makes an assistant useful</h2>\n<p>A Mac assistant needs more than chat. It should understand the active application, identify relevant controls, propose an action, request approval for material changes, verify what happened, and remember enough context to help later. It also needs restraint: no silent destructive actions, no surprise background network calls, and clear permissions.</p>\n<h2>Pace&#39;s model</h2>\n<p>Pace is an Apple Silicon macOS voice and action assistant. In local mode, its planner, screen understanding, speech, retrieval, journals, and meeting synthesis run on the Mac. It can use Apple-native or user-enabled external planner tiers, but off-device paths are explicit, consent-gated, visibly indicated, and recorded in a local privacy audit log. Unattended scheduled work does not silently escalate to the network.</p>\n<p>Pace can read screen context, execute supported actions through its approval and verification pipeline, teach and run local skills, keep bounded local memory, and capture two-track meeting audio for local transcription and note generation. Individual capabilities have their own permissions and opt-ins; “on-device” does not remove the need for macOS microphone, accessibility, screen, calendar, or other relevant access.</p>\n<h2>Who this is for</h2>\n<p>Pace fits people who want a Mac-native assistant with voice, screen context, actions, and memory while keeping local processing as the default. It is not a cross-platform cloud chatbot and does not support Intel Macs.</p>\n<p><strong>CTA:</strong> Download Pace, inspect its privacy model, or continue to the screen-aware and action guides.</p>\n"
  },
  "/screen-aware-ai-assistant-mac": {
    "title": "Screen-aware AI assistant for Mac",
    "description": "Understand how a screen-aware Mac assistant combines accessibility, local vision, interaction state, approval, and post-action verification.",
    "path": "/screen-aware-ai-assistant-mac",
    "intent": "problem and workflow page for people looking for a Mac assistant that understands the screen",
    "schema": [
      "TechArticle",
      "BreadcrumbList"
    ],
    "internalLinks": [
      "/on-device-ai-assistant-mac",
      "/mac-ai-assistant-actions",
      "/private-voice-assistant-mac",
      "/privacy",
      "/download"
    ],
    "markdown": "A screen-aware AI assistant uses the state of the active Mac application to answer questions, guide the user, or perform an approved action. It should not treat a screenshot as unlimited authority. Reliable screen assistance combines the least invasive observation available with accessibility structure, visual grounding when necessary, and verification after each action.\n\n## Three kinds of screen context\n\n1. **Accessibility structure:** roles, labels, values, focus, and actions exposed by macOS. This is usually the best source for semantic controls.\n2. **Visual context:** pixels, OCR, or detected marks for applications where accessibility information is incomplete.\n3. **Interaction state:** the active window, recent user input, and the visible change after an action.\n\nEach source has gaps. Accessibility can be incomplete, visual models can misread coordinates, and a visible change may not prove the intended result. A robust assistant cross-checks them and fails visibly when confidence is insufficient.\n\n## The action loop\n\nA useful loop is observe, plan, request approval when required, act, and verify. For a click, verification might confirm a changed accessibility value or a new window state. For a workflow guide, the assistant should advance only after the user's click matches the expected state. A coordinate alone is not a durable outcome.\n\n## Pace's screen model\n\nPace can use local accessibility context, OCR, and a local vision model. Its click executor scores candidates, verifies the result, and has recovery paths for ambiguous targets. Watch mode records bounded local observations when enabled. Pace can also draw guidance on screen and wait for the user to complete the expected step. Screen and accessibility permissions remain controlled through macOS and Pace's own settings.\n\n## Privacy and limits\n\nIn local mode, screen analysis stays on the Mac. If a user selects an off-device planner tier, Pace shows the external state and records it in the local audit log; capability-specific privacy pins can still require local processing. Users should disable screen or journal sources they do not want and clear local history through settings.\n\n**CTA:** See how approved Mac actions work, review privacy controls, or download Pace.",
    "html": "<p>A screen-aware AI assistant uses the state of the active Mac application to answer questions, guide the user, or perform an approved action. It should not treat a screenshot as unlimited authority. Reliable screen assistance combines the least invasive observation available with accessibility structure, visual grounding when necessary, and verification after each action.</p>\n<h2>Three kinds of screen context</h2>\n<ol>\n<li><strong>Accessibility structure:</strong> roles, labels, values, focus, and actions exposed by macOS. This is usually the best source for semantic controls.</li>\n<li><strong>Visual context:</strong> pixels, OCR, or detected marks for applications where accessibility information is incomplete.</li>\n<li><strong>Interaction state:</strong> the active window, recent user input, and the visible change after an action.</li>\n</ol>\n<p>Each source has gaps. Accessibility can be incomplete, visual models can misread coordinates, and a visible change may not prove the intended result. A robust assistant cross-checks them and fails visibly when confidence is insufficient.</p>\n<h2>The action loop</h2>\n<p>A useful loop is observe, plan, request approval when required, act, and verify. For a click, verification might confirm a changed accessibility value or a new window state. For a workflow guide, the assistant should advance only after the user&#39;s click matches the expected state. A coordinate alone is not a durable outcome.</p>\n<h2>Pace&#39;s screen model</h2>\n<p>Pace can use local accessibility context, OCR, and a local vision model. Its click executor scores candidates, verifies the result, and has recovery paths for ambiguous targets. Watch mode records bounded local observations when enabled. Pace can also draw guidance on screen and wait for the user to complete the expected step. Screen and accessibility permissions remain controlled through macOS and Pace&#39;s own settings.</p>\n<h2>Privacy and limits</h2>\n<p>In local mode, screen analysis stays on the Mac. If a user selects an off-device planner tier, Pace shows the external state and records it in the local audit log; capability-specific privacy pins can still require local processing. Users should disable screen or journal sources they do not want and clear local history through settings.</p>\n<p><strong>CTA:</strong> See how approved Mac actions work, review privacy controls, or download Pace.</p>\n"
  },
  "/private-voice-assistant-mac": {
    "title": "Private voice assistant for Mac",
    "description": "Evaluate a private Mac voice assistant by its audio, planning, storage, permissions, and network boundaries—and see how Pace exposes local and optional external paths.",
    "path": "/private-voice-assistant-mac",
    "intent": "privacy-focused category page for Mac voice assistant buyers",
    "schema": [
      "Article",
      "FAQPage",
      "BreadcrumbList"
    ],
    "internalLinks": [
      "/on-device-ai-assistant-mac",
      "/screen-aware-ai-assistant-mac",
      "/on-device-meeting-notes-mac",
      "/privacy",
      "/faq",
      "/download"
    ],
    "markdown": "A private voice assistant should make its data path understandable. “Private” is not just a model label: it depends on where audio is transcribed, where prompts are planned, where speech is generated, what is stored, which permissions are enabled, and whether a network fallback can occur.\n\n## Ask five questions\n\n1. Where does raw microphone audio go?\n2. Is transcription local, external, or configurable?\n3. Can screen context or conversation history leave the device?\n4. What is stored, for how long, and how can it be cleared?\n5. Does the interface clearly indicate an off-device request before it happens?\n\n## Pace's local path\n\nPace supports local speech recognition, a local planner, local vision, local text-to-speech, and local retrieval on Apple Silicon. Conversation memory, research history, screen-watch observations, app-usage journals, taught skills, and meeting artifacts are stored on the Mac under bounded policies described in the app and documentation. Users can enable, inspect, and clear relevant sources.\n\n## Optional external paths\n\nPace can also use Apple Foundation Models, installed Codex or Claude command-line tools, or user-configured API providers. Those paths are optional and do not become invisible fallbacks. External planner choices require consent, show an off-device indicator, and write a local audit record. Scheduled background work stays local unless its separate consent and soak conditions allow the configured external route. Meeting-note synthesis is privacy-pinned to local processing even when another planner tier is enabled elsewhere.\n\n## Permissions still matter\n\nA local application may need microphone, accessibility, screen recording, contacts, calendar, reminders, or other macOS permissions to perform a requested task. Local processing reduces data transfer; it does not remove the need to grant and review access. Use the minimum set for the capabilities you want.\n\n## Honest boundary\n\nNo local assistant can promise that every optional integration is network-free. Downloading models, fetching a user-requested URL, calling an external MCP server, or choosing a cloud planner uses the network. The useful privacy promise is that the boundary is explicit, controllable, and auditable.\n\n**CTA:** Read Pace's privacy policy and FAQ, then download the app for local mode.",
    "html": "<p>A private voice assistant should make its data path understandable. “Private” is not just a model label: it depends on where audio is transcribed, where prompts are planned, where speech is generated, what is stored, which permissions are enabled, and whether a network fallback can occur.</p>\n<h2>Ask five questions</h2>\n<ol>\n<li>Where does raw microphone audio go?</li>\n<li>Is transcription local, external, or configurable?</li>\n<li>Can screen context or conversation history leave the device?</li>\n<li>What is stored, for how long, and how can it be cleared?</li>\n<li>Does the interface clearly indicate an off-device request before it happens?</li>\n</ol>\n<h2>Pace&#39;s local path</h2>\n<p>Pace supports local speech recognition, a local planner, local vision, local text-to-speech, and local retrieval on Apple Silicon. Conversation memory, research history, screen-watch observations, app-usage journals, taught skills, and meeting artifacts are stored on the Mac under bounded policies described in the app and documentation. Users can enable, inspect, and clear relevant sources.</p>\n<h2>Optional external paths</h2>\n<p>Pace can also use Apple Foundation Models, installed Codex or Claude command-line tools, or user-configured API providers. Those paths are optional and do not become invisible fallbacks. External planner choices require consent, show an off-device indicator, and write a local audit record. Scheduled background work stays local unless its separate consent and soak conditions allow the configured external route. Meeting-note synthesis is privacy-pinned to local processing even when another planner tier is enabled elsewhere.</p>\n<h2>Permissions still matter</h2>\n<p>A local application may need microphone, accessibility, screen recording, contacts, calendar, reminders, or other macOS permissions to perform a requested task. Local processing reduces data transfer; it does not remove the need to grant and review access. Use the minimum set for the capabilities you want.</p>\n<h2>Honest boundary</h2>\n<p>No local assistant can promise that every optional integration is network-free. Downloading models, fetching a user-requested URL, calling an external MCP server, or choosing a cloud planner uses the network. The useful privacy promise is that the boundary is explicit, controllable, and auditable.</p>\n<p><strong>CTA:</strong> Read Pace&#39;s privacy policy and FAQ, then download the app for local mode.</p>\n"
  },
  "/mac-ai-assistant-actions": {
    "title": "Mac AI assistant that can take actions",
    "description": "See how a Mac AI assistant can take approved, typed, verifiable actions through accessibility, app integrations, Shortcuts, tools, and recoverable workflows.",
    "path": "/mac-ai-assistant-actions",
    "intent": "workflow and category page for people seeking an action-taking Mac assistant",
    "schema": [
      "HowTo",
      "TechArticle",
      "BreadcrumbList"
    ],
    "internalLinks": [
      "/on-device-ai-assistant-mac",
      "/screen-aware-ai-assistant-mac",
      "/private-voice-assistant-mac",
      "/faq",
      "/download"
    ],
    "markdown": "A Mac AI assistant that takes actions should do more than generate instructions, but less than silently control the computer. The safe product boundary is an observable action loop: understand the request, inspect current state, propose typed steps, ask for approval when risk requires it, execute through the strongest available interface, verify the result, and preserve an undo or audit trail where possible.\n\n## Prefer semantic actions\n\nUse application APIs, App Intents, Shortcuts, MCP tools, or the macOS Accessibility API when they expose the requested operation. These interfaces carry labels and state that are more durable than raw screen coordinates. Use visual grounding and pointer events as a fallback for applications without sufficient semantic access.\n\n## Separate planning from authority\n\nThe model can propose an action, but policy should decide whether it may run. Read-only navigation, reversible edits, external messages, downloads, and destructive mutations need different treatment. A planner output should be parsed into typed actions and validated before execution.\n\n## Verify after every material step\n\nA click event only proves that input was sent. Verification should inspect the resulting window, control value, file, reminder, message draft, or other expected state. If the result is ambiguous, stop or recover; do not continue a long workflow on an assumed success.\n\n## Pace's action stack\n\nPace includes a typed tool registry, a plan-act-observe loop, application integrations, App Intents and deeplinks, accessibility and pointer execution, click scoring and recovery, undo for supported reversible mutations, failure narration, and local action history. Users can also record literal flows, install recipes, or teach natural-language skills that are re-grounded against the current screen. MCP connections and external services are optional.\n\n## Good first workflows\n\nStart with bounded tasks whose outcome can be checked: open an application, create a reminder, draft rather than send an email, navigate a known interface, record a repeatable flow, or guide the user through an unfamiliar screen. Expand authority only after the verification path is reliable.\n\n**CTA:** Review Pace's action and privacy model, then download it for a supported Mac.",
    "html": "<p>A Mac AI assistant that takes actions should do more than generate instructions, but less than silently control the computer. The safe product boundary is an observable action loop: understand the request, inspect current state, propose typed steps, ask for approval when risk requires it, execute through the strongest available interface, verify the result, and preserve an undo or audit trail where possible.</p>\n<h2>Prefer semantic actions</h2>\n<p>Use application APIs, App Intents, Shortcuts, MCP tools, or the macOS Accessibility API when they expose the requested operation. These interfaces carry labels and state that are more durable than raw screen coordinates. Use visual grounding and pointer events as a fallback for applications without sufficient semantic access.</p>\n<h2>Separate planning from authority</h2>\n<p>The model can propose an action, but policy should decide whether it may run. Read-only navigation, reversible edits, external messages, downloads, and destructive mutations need different treatment. A planner output should be parsed into typed actions and validated before execution.</p>\n<h2>Verify after every material step</h2>\n<p>A click event only proves that input was sent. Verification should inspect the resulting window, control value, file, reminder, message draft, or other expected state. If the result is ambiguous, stop or recover; do not continue a long workflow on an assumed success.</p>\n<h2>Pace&#39;s action stack</h2>\n<p>Pace includes a typed tool registry, a plan-act-observe loop, application integrations, App Intents and deeplinks, accessibility and pointer execution, click scoring and recovery, undo for supported reversible mutations, failure narration, and local action history. Users can also record literal flows, install recipes, or teach natural-language skills that are re-grounded against the current screen. MCP connections and external services are optional.</p>\n<h2>Good first workflows</h2>\n<p>Start with bounded tasks whose outcome can be checked: open an application, create a reminder, draft rather than send an email, navigate a known interface, record a repeatable flow, or guide the user through an unfamiliar screen. Expand authority only after the verification path is reliable.</p>\n<p><strong>CTA:</strong> Review Pace&#39;s action and privacy model, then download it for a supported Mac.</p>\n"
  },
  "/on-device-meeting-notes-mac": {
    "title": "On-device meeting notes for Mac",
    "description": "Learn how on-device meeting notes capture two audio tracks, transcribe and summarize locally, ground action items, and keep retention under user control.",
    "path": "/on-device-meeting-notes-mac",
    "intent": "use-case page for people seeking private local meeting notes on Mac",
    "schema": [
      "HowTo",
      "FAQPage",
      "BreadcrumbList"
    ],
    "internalLinks": [
      "/on-device-ai-assistant-mac",
      "/private-voice-assistant-mac",
      "/privacy",
      "/faq",
      "/download"
    ],
    "markdown": "On-device meeting notes keep capture, transcription, and synthesis on the Mac instead of uploading a conversation to a hosted note-taking service. This matters most when the meeting contains customer data, hiring discussions, strategy, credentials, or other information that should not become a third party's default input.\n\n## The local pipeline\n\nA complete workflow captures the user's microphone and the other side of the call, preserves the tracks, transcribes them locally, segments the conversation, and generates a summary, decisions, and action items with links back to source moments. Storage location, retention, and deletion should be visible.\n\n## Pace meeting mode\n\nPace records two local audio tracks for a meeting: the user's microphone and system or call audio. When the meeting stops, local transcription feeds a privacy-pinned local note model. The output includes structured notes and transcript-grounded action items. Meeting files are ordinary local artifacts under Pace's application-support directory and use a configurable retention policy documented in the product; the current default described by the public FAQ is 30 days.\n\nThe privacy pin is important: enabling a cloud or command-line planner elsewhere in Pace does not allow meeting-note synthesis to use it. A user can still choose external applications or workflows outside that boundary, but Pace's meeting synthesis path remains local.\n\n## What to evaluate\n\n- Does the app capture both sides reliably on the target Mac?\n- Are transcripts and notes generated without a network fallback?\n- Can an action item show the source quote or timestamp?\n- Are files easy to locate, export, and delete?\n- Is retention configurable and enforced?\n- Are microphone and screen or system-audio permissions clear?\n\n## Honest limits\n\nLocal transcription and synthesis consume memory, storage, and battery. Accuracy depends on audio quality, speakers, language, and the installed local models. A generated summary should be treated as a draft, and important decisions should be checked against the transcript.\n\n**CTA:** Review Pace's meeting privacy details and FAQ, then download Pace for Apple Silicon.",
    "html": "<p>On-device meeting notes keep capture, transcription, and synthesis on the Mac instead of uploading a conversation to a hosted note-taking service. This matters most when the meeting contains customer data, hiring discussions, strategy, credentials, or other information that should not become a third party&#39;s default input.</p>\n<h2>The local pipeline</h2>\n<p>A complete workflow captures the user&#39;s microphone and the other side of the call, preserves the tracks, transcribes them locally, segments the conversation, and generates a summary, decisions, and action items with links back to source moments. Storage location, retention, and deletion should be visible.</p>\n<h2>Pace meeting mode</h2>\n<p>Pace records two local audio tracks for a meeting: the user&#39;s microphone and system or call audio. When the meeting stops, local transcription feeds a privacy-pinned local note model. The output includes structured notes and transcript-grounded action items. Meeting files are ordinary local artifacts under Pace&#39;s application-support directory and use a configurable retention policy documented in the product; the current default described by the public FAQ is 30 days.</p>\n<p>The privacy pin is important: enabling a cloud or command-line planner elsewhere in Pace does not allow meeting-note synthesis to use it. A user can still choose external applications or workflows outside that boundary, but Pace&#39;s meeting synthesis path remains local.</p>\n<h2>What to evaluate</h2>\n<ul>\n<li>Does the app capture both sides reliably on the target Mac?</li>\n<li>Are transcripts and notes generated without a network fallback?</li>\n<li>Can an action item show the source quote or timestamp?</li>\n<li>Are files easy to locate, export, and delete?</li>\n<li>Is retention configurable and enforced?</li>\n<li>Are microphone and screen or system-audio permissions clear?</li>\n</ul>\n<h2>Honest limits</h2>\n<p>Local transcription and synthesis consume memory, storage, and battery. Accuracy depends on audio quality, speakers, language, and the installed local models. A generated summary should be treated as a draft, and important decisions should be checked against the transcript.</p>\n<p><strong>CTA:</strong> Review Pace&#39;s meeting privacy details and FAQ, then download Pace for Apple Silicon.</p>\n"
  }
};

