"""
Hand-written goal ↔ on-screen-element catalog for the next-step router's
abstract-click scenarios (loaded by generate-router-step-states.py with
--extra-scenarios-only). Pure data, no logic.

Why it exists: the first ModernBERT student routed goal-phrased click requests
("i want to leave a tip" with a gratuity button on screen) to ASK_USER, because
every click it had seen named its target literally. Each entry here pairs a
GOAL, phrased the way people say it, with the one element on a realistic screen
that achieves it.

Shape of APP_SCREEN_CONTEXTS entries:
    "app":      where the screen lives (only used for coverage stats)
    "elements": every element that can appear on that screen, as (role, label, hover/help text)
    "goals":    (target_label, alternate_labels, phrasings)
        target_label      the element that satisfies every phrasing
        alternate_labels  other elements on the same screen that ALSO genuinely satisfy those
                          phrasings. abstract_click screens never show them (so exactly one element
                          fits); abstract_ambiguous screens show target + one alternate (→ ASK_USER).
        phrasings         independent ways to state the goal (not slot permutations)

Rules followed while writing it:
  - Targets are never destructive or irreversible (delete/send/pay/buy/leave stay distractors only),
    so the right answer is a click, not a confirmation.
  - No harness fixture instance is reused: no Bookmark/Like/Share trio, no tip/gratuity button,
    no spam "Report" flag, no "take that back"/Undo, no Lightroom/Figma/Notion/Zoom/Slack dock sets.
    The generator additionally rejects any screen sharing two labels with a fixture's label set and
    any request within Jaccard 0.6 of a fixture USER line.
"""

APP_SCREEN_CONTEXTS = [
    {
        "app": "Mail (reading a message)",
        "elements": [
            ("button", "Reply All", "Reply to everyone on the thread"), ("button", "Forward", ""),
            ("button", "Archive", "Move out of the inbox"), ("button", "Move to Junk", "Mark as junk mail"),
            ("button", "Flag", "Flag for follow-up"), ("button", "Mark as Unread", ""),
            ("button", "Move", "Move to folder…"), ("button", "Print", ""), ("button", "Mute Thread", "Stop notifications for this conversation"),
            ("button", "Snooze", "Bring back later"), ("link", "Unsubscribe", "Unsubscribe from this mailing list"),
            ("button", "Save Attachments", "Download all attachments"), ("button", "Translate", "Translate message"),
            ("button", "Delete", ""), ("button", "Block Sender", ""),
        ],
        "goals": [
            ("Reply All", [], ["make sure everyone on this thread sees my answer", "respond to the whole group, not just her",
                               "answer everybody who got this email"]),
            ("Forward", [], ["pass this along to someone who wasn't on it", "i want to send this on to my accountant",
                             "get this email over to legal as is"]),
            ("Archive", [], ["get this out of my inbox but keep it somewhere", "i'm done with this one, file it away",
                             "clear it from the inbox without getting rid of it"]),
            ("Flag", ["Snooze"], ["i need to come back to this one", "make sure i don't forget to deal with this"]),
            ("Flag", [], ["make this stand out in the list so i follow up", "put a marker on this one so it's easy to spot"]),
            ("Snooze", [], ["hide this until tomorrow morning", "make this pop back up at the top on monday",
                            "i can't deal with it now, have it reappear this evening"]),
            ("Mark as Unread", [], ["make it look like i haven't opened this yet", "put the blue dot back on this",
                                    "keep this looking new so it catches my eye later"]),
            ("Move to Junk", [], ["this is a phishing attempt, get it out of here", "that sender is a scammer, teach the filter",
                                  "this is obviously junk mail pretending to be my bank"]),
            ("Move to Junk", ["Unsubscribe"], ["i never asked for these newsletters, make them stop showing up"]),
            ("Move", [], ["put this in my receipts folder", "file this under the house project folder",
                          "this belongs with my tax stuff, put it there"]),
            ("Print", [], ["i need a paper copy of this", "get this onto paper for the meeting", "run this off on the printer"]),
            ("Save Attachments", [], ["save the files they sent me to my computer", "grab all the pdfs attached to this",
                                      "i want the attachments on my drive"]),
            ("Translate", [], ["this is in german, make it readable for me", "show me this email in english",
                               "i can't read portuguese, convert it"]),
            ("Mute Thread", [], ["stop notifying me about this conversation", "i don't want any more pings from this chain",
                                 "this reply-all storm is driving me nuts, silence it"]),
        ],
    },
    {
        "app": "Mail (composing)",
        "elements": [
            ("button", "Attach", "Attach a file"), ("button", "Add Image", "Insert an image inline"),
            ("button", "Hyperlink", "Turn selected text into a link"), ("text_field", "Cc", ""), ("text_field", "Bcc", "Blind copy"),
            ("button", "Send Later", "Schedule this message"), ("button", "Importance", "Mark as high importance"),
            ("button", "Lock", "Encrypt this message"), ("button", "Check Spelling", ""), ("button", "Signature", "Insert signature"),
            ("button", "Send", ""), ("button", "Discard", ""), ("button", "Emoji", ""),
        ],
        "goals": [
            ("Attach", [], ["i need to include the signed contract with this", "put the spreadsheet in with this email",
                            "include the deck file so they have it"]),
            ("Attach", ["Add Image"], ["include the photo from the site visit with this"]),
            ("Add Image", [], ["put the chart picture right in the middle of the text", "drop the screenshot inline under this paragraph"]),
            ("Hyperlink", [], ["make these words go to our pricing page", "turn this phrase into something they can click"]),
            ("Bcc", [], ["copy my boss without the others seeing", "secretly include my lawyer on this",
                         "add someone the recipients won't know about"]),
            ("Cc", ["Bcc"], ["keep my manager in the loop on this"]),
            ("Cc", [], ["loop dana in openly so everyone sees she's included", "visibly copy the team lead so it's on record"]),
            ("Send Later", [], ["have this go out tomorrow at nine instead of now", "don't send it yet, deliver it monday morning",
                                "time this to land in their inbox after the holiday"]),
            ("Importance", [], ["make it obvious to them this is urgent", "mark this as high priority so they read it first"]),
            ("Lock", [], ["make sure only the recipient can read this", "protect this so nobody else can open it in transit"]),
            ("Check Spelling", [], ["make sure i didn't misspell anything", "catch my typos before this goes out",
                                    "proofread the words for spelling mistakes"]),
            ("Signature", [], ["add my name and title at the bottom", "put my usual sign-off on this"]),
        ],
    },
    {
        "app": "Web browser toolbar",
        "elements": [
            ("button", "Previous Page", ""), ("button", "Reload", "Reload this page"), ("button", "Reader View", "Show article without clutter"),
            ("button", "Find on Page", ""), ("button", "Translate Page", ""), ("button", "New Private Window", ""),
            ("button", "Reading List", "Save to Reading List"), ("button", "Favorites", "Add page to favorites"),
            ("button", "Pin Tab", ""), ("button", "History", ""), ("button", "Picture in Picture", ""), ("button", "Mute Tab", ""),
            ("button", "Zoom In", ""), ("button", "Download Manager", "Show downloads"), ("button", "Print Page", ""),
            ("button", "Tab Overview", ""),
        ],
        "goals": [
            ("Reader View", [], ["strip this page down to just the article text", "get rid of all the ads and sidebars so i can read",
                                 "make this news story clean and readable"]),
            ("Find on Page", [], ["where does it mention the refund policy on here", "search this page for the word deadline",
                                  "jump to where it talks about shipping costs"]),
            ("Translate Page", [], ["this site is in japanese, make it english", "i can't read this french page, convert it"]),
            ("New Private Window", [], ["i want to browse without it saving my history", "open something incognito",
                                        "look up a gift without it showing in my history"]),
            ("Reading List", ["Favorites"], ["keep this so i can come back to it", "hang onto this page for later"]),
            ("Reading List", [], ["stash this article to finish on the train", "queue this up to read tonight offline"]),
            ("Favorites", [], ["put this site in my top sites so it's one click away", "add this to the sites i visit every day"]),
            ("Previous Page", [], ["go back to where i was before this", "take me back one page", "that link was wrong, return to the last page"]),
            ("Reload", [], ["this page looks stuck, try loading it again", "get the latest version of this page",
                            "the scores aren't updating, refresh it"]),
            ("Pin Tab", [], ["keep this tab stuck on the left permanently", "make this tab always stay open"]),
            ("History", [], ["what was that site i visited yesterday afternoon", "show me the pages i went to this morning"]),
            ("Picture in Picture", [], ["pop this video out so it floats while i work", "keep the video playing in a corner over my other windows"]),
            ("Mute Tab", [], ["this tab is blasting an ad, silence just this one", "kill the sound coming from this page only"]),
            ("Zoom In", [], ["the text on this site is tiny, make it bigger", "enlarge this page, i can barely read it"]),
            ("Download Manager", [], ["where did that file i just grabbed go", "show me the stuff i've downloaded"]),
            ("Print Page", [], ["get a hard copy of this recipe", "print out this boarding pass"]),
            ("Tab Overview", [], ["show me all my open tabs at once", "i have too many tabs, let me see them all as a grid"]),
        ],
    },
    {
        "app": "Shopping product page",
        "elements": [
            ("button", "Add to Cart", ""), ("button", "Buy Now", ""), ("button", "Save for Later", ""),
            ("button", "Add to Wishlist", ""), ("button", "Compare", "Compare with similar items"), ("link", "Size Guide", ""),
            ("button", "Notify Me", "Email me when back in stock"), ("button", "Gift Options", ""), ("text_field", "Coupon Code", ""),
            ("link", "Questions & Answers", ""), ("button", "Rate Product", ""), ("link", "Track Package", ""),
            ("link", "Return Item", ""), ("button", "Subscribe & Save", "Deliver every month"), ("button", "Chat with Seller", ""),
            ("button", "See Similar", ""),
        ],
        "goals": [
            ("Add to Cart", [], ["i want this one, put it in my basket but don't check out", "add this to what i'm getting",
                                 "throw it in with the rest of my order"]),
            ("Save for Later", [], ["move this out of my cart for now without removing it", "i'll decide on this next payday, park it in the cart"]),
            ("Add to Wishlist", ["Save for Later"], ["i'm not ready to buy, keep it around"]),
            ("Add to Wishlist", [], ["put this on the list of things i want for my birthday", "add it to my gift ideas list"]),
            ("Size Guide", [], ["i'm not sure a medium will fit me", "how do these run, show me the measurements",
                                "is a 42 the same as a us 9 in these"]),
            ("Compare", [], ["how does this stack up against the two i already picked", "put this side by side with the others i chose"]),
            ("See Similar", [], ["show me other ones like this but cheaper", "find alternatives to this jacket"]),
            ("Notify Me", [], ["it's sold out, let me know when it's back", "tell me when they restock this"]),
            ("Gift Options", [], ["this is a present, add a message and wrap it", "make this look like a gift when it arrives"]),
            ("Coupon Code", [], ["i have a promo code from their email", "use the discount code my friend gave me"]),
            ("Questions & Answers", [], ["i want to ask other buyers if this works with a mac", "has anyone asked whether it's waterproof"]),
            ("Rate Product", [], ["i want to give this thing five stars", "let other shoppers know this broke in a week"]),
            ("Track Package", [], ["where's my order right now", "when is my delivery arriving"]),
            ("Return Item", [], ["this doesn't fit, i want to send it back", "start getting my money back for this, it arrived broken"]),
            ("Subscribe & Save", [], ["have this delivered automatically every month", "set this up as a recurring order"]),
            ("Chat with Seller", [], ["i need to message whoever is selling this", "ask the shop directly about bulk pricing"]),
        ],
    },
    {
        "app": "Video player",
        "elements": [
            ("button", "Subscribe", ""), ("button", "Thumbs Up", ""), ("button", "Thumbs Down", ""), ("button", "Captions", "Subtitles/closed captions"),
            ("button", "Playback Speed", ""), ("button", "Skip Ad", ""), ("button", "Watch Later", ""), ("button", "Save to Playlist", ""),
            ("button", "Full Screen", ""), ("button", "Theater Mode", ""), ("button", "Chapters", ""), ("button", "Autoplay", "Autoplay next video"),
            ("button", "Clip", "Create a clip"), ("button", "Next Video", ""), ("button", "Quality", "Video resolution"),
        ],
        "goals": [
            ("Captions", [], ["i can't have sound on in here, show the words", "turn on subtitles", "what are they saying, put the text on screen"]),
            ("Playback Speed", [], ["this guy talks so slowly, speed him up", "play it at one and a half times", "slow this tutorial down so i can follow"]),
            ("Skip Ad", [], ["get me past this commercial", "i don't want to sit through this promo"]),
            ("Watch Later", ["Save to Playlist"], ["keep this to watch tonight", "i don't have time now, save it for later"]),
            ("Save to Playlist", [], ["add this to my workout videos collection", "put this in the cooking list i made"]),
            ("Thumbs Up", [], ["i loved this video, let them know", "show the creator some appreciation"]),
            ("Thumbs Down", [], ["i didn't like this at all, tell the algorithm", "this was clickbait, register that i disliked it"]),
            ("Subscribe", [], ["i want to see everything this channel posts", "follow this creator's uploads"]),
            ("Full Screen", [], ["make the video take up the whole display", "blow this up to the entire monitor"]),
            ("Theater Mode", [], ["make the player wider but keep the page around it", "bigger player, but not the whole screen"]),
            ("Chapters", [], ["jump to the part where they talk about pricing", "skip to the section on setup"]),
            ("Autoplay", [], ["stop it from starting another video when this ends", "don't roll into the next one automatically"]),
            ("Clip", [], ["cut out that ten second moment to share", "grab just the funny bit as a short clip"]),
            ("Next Video", [], ["move on to the next one in this series", "go to the following episode in the playlist"]),
            ("Quality", [], ["it looks blurry, make it hd", "this is buffering, drop the resolution"]),
        ],
    },
    {
        "app": "Music app (now playing)",
        "elements": [
            ("button", "Lyrics", ""), ("button", "Go to Artist", ""), ("button", "Go to Album", ""), ("button", "Song Radio", "Start a station from this song"),
            ("button", "Devices", "Connect to a device"), ("button", "Queue", "Up next"), ("button", "Add to Playlist", ""),
            ("button", "Heart", "Save to Liked Songs"), ("button", "Equalizer", ""), ("button", "Download", "Available offline"),
            ("button", "Credits", "Song credits"), ("button", "Share Song", ""),
        ],
        "goals": [
            ("Lyrics", [], ["what are they singing, show me the words", "i want to sing along to this"]),
            ("Go to Artist", [], ["who made this, show me more of their stuff", "take me to this singer's page"]),
            ("Go to Album", [], ["show me the rest of the record this is from", "what else is on this album"]),
            ("Song Radio", [], ["play more stuff that sounds like this", "keep going with tracks in this same vibe"]),
            ("Devices", [], ["play this on the kitchen speaker instead", "move the music over to the living room tv"]),
            ("Queue", [], ["what's coming up after this one", "show me the songs lined up next"]),
            ("Add to Playlist", [], ["put this on my road trip mix", "add this track to my running playlist"]),
            ("Heart", [], ["i love this track, keep it in my liked songs", "remember that i like this song"]),
            ("Equalizer", [], ["boost the bass a little", "the treble sounds harsh, adjust the sound profile"]),
            ("Download", [], ["make this playlist work offline for my flight", "keep these songs on the laptop for the plane"]),
            ("Credits", [], ["who produced this song", "who wrote this, show the songwriters"]),
        ],
    },
    {
        "app": "Team chat channel",
        "elements": [
            ("button", "Reply in Thread", ""), ("button", "Add Reaction", ""), ("button", "Pin Message", ""), ("button", "Remind Me", "Remind me about this message"),
            ("button", "Do Not Disturb", "Pause notifications"), ("button", "Set Status", ""), ("button", "Start Huddle", "Start a voice call"),
            ("button", "Edit Message", ""), ("button", "Copy Link", "Copy link to message"), ("button", "Channel Details", "Members and settings"),
            ("button", "Mark Unread", ""), ("button", "Delete Message", ""), ("button", "Leave Channel", ""),
        ],
        "goals": [
            ("Reply in Thread", [], ["answer this without cluttering the main channel", "respond just under that message",
                                     "keep my answer attached to her question"]),
            ("Add Reaction", [], ["give that a thumbs up emoji", "react with a laughing face", "acknowledge it with an emoji instead of typing"]),
            ("Pin Message", [], ["keep this announcement at the top of the channel for everyone", "make this stick so new people see it"]),
            ("Remind Me", ["Mark Unread"], ["i'll deal with this message later"]),
            ("Remind Me", [], ["bring this message back to me in an hour", "nudge me about this at three"]),
            ("Mark Unread", [], ["leave this showing as new in the sidebar", "keep the channel bold so i notice it again"]),
            ("Do Not Disturb", [], ["i need to focus, stop all the notifications for a while", "silence everything until lunch"]),
            ("Set Status", [], ["let people know i'm out sick today", "show everyone i'm in meetings all afternoon"]),
            ("Start Huddle", [], ["let's just talk this out by voice real quick", "faster to talk, get us on audio in this channel"]),
            ("Edit Message", [], ["i made a typo in what i just posted, change it", "fix the date in my last message"]),
            ("Copy Link", [], ["i need a link to this message to paste into the doc", "grab a url pointing at this exact post"]),
            ("Channel Details", [], ["see this channel's members and settings", "change this channel's topic and description"]),
        ],
    },
    {
        "app": "Document editor",
        "elements": [
            ("button", "Comment", "Add comment"), ("button", "Suggesting", "Suggest edits"), ("button", "Version History", ""),
            ("button", "Insert Table", ""), ("button", "Insert Chart", ""), ("button", "Export PDF", "Download as PDF"),
            ("button", "Find and Replace", ""), ("button", "Outline", "Show document outline"), ("button", "Voice Typing", ""),
            ("button", "Line Spacing", ""), ("button", "Page Setup", ""), ("button", "Word Count", ""), ("button", "Styles", "Paragraph styles"),
            ("button", "Share Doc", ""), ("button", "Clear Formatting", ""),
        ],
        "goals": [
            ("Comment", [], ["leave a note on this sentence for jordan", "ask a question next to this paragraph without changing it"]),
            ("Suggesting", [], ["make my edits show up as proposals the owner can accept", "change this without actually overwriting their text"]),
            ("Version History", [], ["what did this doc look like last tuesday", "see who rewrote the intro and when"]),
            ("Insert Table", [], ["put a grid here with three columns", "lay these out in rows and columns"]),
            ("Insert Chart", [], ["visualize these numbers as a bar graph", "add a pie graph of the budget split"]),
            ("Export PDF", [], ["i need this as a pdf to hand in", "turn this document into a file i can attach that won't change"]),
            ("Find and Replace", [], ["change every acme in here to globex", "swap the old product name everywhere in the doc"]),
            ("Outline", [], ["show the list of headings so i can jump around", "give me a sidebar of the sections"]),
            ("Voice Typing", [], ["let me dictate instead of typing", "i want to talk and have it write"]),
            ("Line Spacing", [], ["double space this whole thing", "add more room between the lines"]),
            ("Page Setup", [], ["switch the page to landscape", "change the margins to one inch"]),
            ("Word Count", [], ["how many words have i written so far", "am i under the 500 word limit"]),
            ("Styles", [], ["make this line a section heading", "turn this into a title style"]),
            ("Clear Formatting", [], ["this pasted text has weird fonts, make it plain", "strip the bold and colors off this"]),
        ],
    },
    {
        "app": "Spreadsheet",
        "elements": [
            ("button", "Sort", "Sort A to Z"), ("button", "Filter", ""), ("button", "Freeze", "Freeze top row"), ("button", "AutoSum", "Σ"),
            ("button", "Conditional Formatting", ""), ("button", "Merge Cells", ""), ("button", "Wrap Text", ""), ("button", "Pivot Table", ""),
            ("button", "Currency", "Format as currency"), ("button", "Percent", "Format as percent"), ("button", "Data Validation", ""),
            ("button", "Chart", "Insert chart"), ("button", "Remove Duplicates", ""), ("button", "Comment", ""),
        ],
        "goals": [
            ("Sort", [], ["put these names in alphabetical order", "order the rows from smallest to largest"]),
            ("Filter", [], ["only show the rows from march", "hide everything except the open invoices"]),
            ("Freeze", [], ["keep the header row visible while i scroll down", "make the column titles stay put"]),
            ("AutoSum", [], ["add up this column", "give me the total of these cells"]),
            ("Conditional Formatting", [], ["make anything over budget turn red automatically", "highlight the overdue dates in orange"]),
            ("Merge Cells", [], ["combine these two cells into one big one", "make this title span across the columns"]),
            ("Wrap Text", [], ["the text is spilling over, keep it inside the cell", "let the long notes break onto multiple lines in the cell"]),
            ("Pivot Table", [], ["summarize sales by region", "roll these transactions up by category"]),
            ("Currency", [], ["show these numbers as dollars", "put a dollar sign and two decimals on these"]),
            ("Percent", [], ["display these as percentages", "turn the decimals into percents"]),
            ("Data Validation", [], ["make this column only accept dates", "give this cell a dropdown of yes or no"]),
            ("Chart", [], ["turn this table into a graph", "plot revenue over the months"]),
        ],
    },
    {
        "app": "System Settings",
        "elements": [
            ("option", "Wi-Fi", ""), ("option", "Bluetooth", ""), ("option", "Displays", ""), ("option", "Battery", ""), ("option", "Appearance", ""),
            ("option", "Wallpaper", ""), ("option", "Trackpad", ""), ("option", "Keyboard", ""), ("option", "Focus", ""), ("option", "Notifications", ""),
            ("option", "Screen Time", ""), ("option", "Privacy & Security", ""), ("option", "Printers & Scanners", ""), ("option", "Accessibility", ""),
            ("option", "Users & Groups", ""), ("option", "Software Update", ""), ("option", "Lock Screen", ""), ("option", "Sound", ""),
        ],
        "goals": [
            ("Bluetooth", [], ["my headphones won't connect", "pair my new wireless keyboard"]),
            ("Wi-Fi", [], ["i can't get online, check the network", "join the coffee shop's network"]),
            ("Displays", [], ["set up my second monitor", "make the external screen sit to the left of the laptop"]),
            ("Battery", [], ["what's draining my laptop so fast", "turn on low power mode"]),
            ("Appearance", [], ["make the whole system dark", "i want the light theme back"]),
            ("Wallpaper", [], ["change my desktop background", "put a different picture behind my windows"]),
            ("Trackpad", [], ["make scrolling go the other way", "turn on tap to click"]),
            ("Keyboard", [], ["add a spanish keyboard layout", "make held keys repeat faster"]),
            ("Focus", ["Notifications"], ["don't let anything interrupt me during work hours"]),
            ("Focus", [], ["set up a mode for when i'm driving", "create a work mode that only lets my boss through"]),
            ("Notifications", [], ["stop the news app from showing banners", "hide message previews on the lock screen"]),
            ("Screen Time", [], ["limit how long the kids can play games", "set a daily cap on social apps"]),
            ("Privacy & Security", [], ["let the video app use my camera", "which apps can see my location"]),
            ("Printers & Scanners", [], ["add the office printer", "my printer isn't showing up, set it up"]),
            ("Accessibility", [], ["have the computer read text out loud to me", "make the mouse pointer larger"]),
            ("Users & Groups", [], ["add an account for my daughter", "make a separate login for guests"]),
            ("Software Update", [], ["check if there's a new version of macos", "is my mac up to date"]),
            ("Lock Screen", [], ["make the screen lock sooner when i walk away", "require my password right after sleep"]),
            ("Sound", [], ["switch the output to my desk speakers", "change the alert noise"]),
        ],
    },
    {
        "app": "Maps place card",
        "elements": [
            ("button", "Directions", ""), ("button", "Transit", ""), ("button", "Walking", ""), ("button", "Satellite", ""),
            ("button", "Traffic", ""), ("button", "Share ETA", ""), ("button", "Save Place", "Add to favorites"), ("button", "Call", ""),
            ("link", "Website", ""), ("button", "Look Around", "Street-level view"), ("button", "Search Nearby", ""), ("button", "Report an Issue", ""),
        ],
        "goals": [
            ("Directions", [], ["how do i get there from here", "plan a route to this place"]),
            ("Transit", [], ["i'm taking the bus, show me that route", "what train gets me there"]),
            ("Walking", [], ["i'd rather go on foot", "how long would it take to walk"]),
            ("Satellite", [], ["show me what it actually looks like from above", "i want the aerial photo view"]),
            ("Traffic", [], ["is the highway backed up right now", "show me where the jams are"]),
            ("Share ETA", [], ["let my wife know when i'll get there", "send my arrival time to the person i'm meeting"]),
            ("Save Place", [], ["remember this restaurant for next time", "keep this spot in my places list"]),
            ("Call", [], ["phone this store and ask if they're open", "ring them up to check for a table"]),
            ("Website", [], ["open this restaurant's own site", "see their menu on their webpage"]),
            ("Look Around", [], ["show me what the entrance looks like from the street", "i want to see the storefront before i go"]),
            ("Search Nearby", [], ["are there gas stations around here", "find coffee close to this spot"]),
            ("Report an Issue", [], ["the pin is in the wrong place, tell them", "this business closed years ago, flag that on the map"]),
        ],
    },
    {
        "app": "Calendar event details",
        "elements": [
            ("button", "Join Meeting", "Join video call"), ("button", "Accept", ""), ("button", "Maybe", ""), ("button", "Decline", ""),
            ("button", "Propose New Time", ""), ("button", "Add Guests", ""), ("button", "Email Guests", ""), ("link", "Get Directions", ""),
            ("button", "Duplicate Event", ""), ("button", "Edit Event", ""), ("button", "Delete Event", ""),
        ],
        "goals": [
            ("Join Meeting", [], ["connect me to this meeting's video", "i'm late, get me into the call that's starting"]),
            ("Accept", [], ["tell them i'll be there", "rsvp yes to this"]),
            ("Maybe", [], ["i might come, i'm not sure yet", "say i'm tentative"]),
            ("Propose New Time", [], ["this slot doesn't work, suggest thursday instead", "ask if we can do this an hour later"]),
            ("Add Guests", [], ["invite priya to this too", "get the design team on this invite"]),
            ("Email Guests", [], ["write to everyone who's coming", "message all the attendees about parking"]),
            ("Get Directions", [], ["how do i get to where this meeting is", "route me to this event's address"]),
            ("Duplicate Event", [], ["make another one just like this for next week", "copy this meeting to a new date"]),
            ("Edit Event", [], ["change the location on this to room 4b", "fix the start time on this event"]),
        ],
    },
    {
        "app": "Photo editor",
        "elements": [
            ("button", "Crop", ""), ("button", "Rotate", ""), ("button", "Auto-Enhance", ""), ("button", "Red-Eye", ""), ("button", "Filters", ""),
            ("button", "Light", "Exposure, brilliance, shadows"), ("button", "Straighten", ""), ("button", "Hide Photo", ""),
            ("button", "Revert to Original", ""), ("button", "Favorite", ""), ("button", "Duplicate", ""), ("button", "Delete", ""),
        ],
        "goals": [
            ("Crop", [], ["cut out the stuff around the edges", "trim this down to just the two of us"]),
            ("Rotate", [], ["it's sideways, turn it upright", "this came out upside down"]),
            ("Auto-Enhance", [], ["just make this look better automatically", "one-click fix the colors for me"]),
            ("Red-Eye", [], ["everyone's eyes are glowing red", "fix the creepy flash eyes"]),
            ("Filters", [], ["give it a black and white look", "make it look like an old film photo"]),
            ("Light", [], ["the picture is underexposed, lighten it up", "bring out detail in the shadows"]),
            ("Straighten", [], ["the horizon is tilted", "the building looks crooked, level it"]),
            ("Hide Photo", [], ["keep this one out of my main library", "i don't want this showing in my memories"]),
            ("Revert to Original", [], ["go back to the photo exactly as it was taken", "throw away every edit on this picture"]),
            ("Favorite", [], ["this is one of my best shots, mark it as a keeper", "add this to the ones i love most"]),
            ("Duplicate", [], ["make a copy before i mess with it", "i want a second version to experiment on"]),
        ],
    },
    {
        "app": "Food delivery order",
        "elements": [
            ("button", "Customize", "Choose toppings"), ("button", "Schedule Order", "Order for later"), ("button", "Group Order", ""),
            ("text_field", "Delivery Instructions", ""), ("button", "Pickup", ""), ("button", "Contact Driver", ""), ("link", "Track Order", ""),
            ("link", "Allergen Info", ""), ("button", "Rate Driver", ""), ("button", "Place Order", ""), ("button", "Cancel Order", ""),
            ("button", "Add Utensils", ""),
        ],
        "goals": [
            ("Customize", [], ["i want extra cheese and no onions on this", "swap the fries for a salad on this meal"]),
            ("Schedule Order", [], ["have this arrive at seven instead of now", "set it up to come tomorrow at lunch"]),
            ("Group Order", [], ["let my coworkers add their own food to this", "start an order the whole office can join"]),
            ("Delivery Instructions", [], ["tell the driver to leave it at the side door", "the buzzer's broken, let them know to call"]),
            ("Pickup", [], ["i'll grab it myself, no delivery", "i'm walking past, i'll collect it at the counter"]),
            ("Contact Driver", [], ["the courier seems lost, let me talk to them", "message the person bringing my food"]),
            ("Track Order", [], ["how far away is my food", "where is the delivery right now"]),
            ("Allergen Info", [], ["does this dish have peanuts in it", "check whether this is gluten free"]),
            ("Rate Driver", [], ["the courier was great, give them a good score", "the delivery guy was rude, rate him low"]),
            ("Add Utensils", [], ["i need a fork and napkins with this", "include plastic cutlery please"]),
        ],
    },
    {
        "app": "Code editor",
        "elements": [
            ("button", "Debug", "Start debugging"), ("button", "Run", "Run without debugging"), ("button", "Terminal", "Toggle terminal"),
            ("button", "Source Control", ""), ("button", "Extensions", ""), ("button", "Format Document", ""), ("button", "Split Editor", ""),
            ("menu_item", "Go to Definition", ""), ("button", "Problems", "Errors and warnings"), ("button", "Command Palette", ""),
            ("button", "Pull", "Pull from remote"), ("button", "Toggle Breakpoint", ""), ("button", "Commit", ""), ("button", "Push", ""),
            ("button", "Find in Files", ""),
        ],
        "goals": [
            ("Debug", [], ["step through this code line by line", "pause it when it crashes so i can inspect variables"]),
            ("Run", ["Debug"], ["try running this script"]),
            ("Terminal", [], ["i need a command line down here", "give me a shell inside the editor"]),
            ("Source Control", [], ["see what files i've changed", "review my diff before committing"]),
            ("Extensions", [], ["install a python plugin", "find an add-on for markdown preview"]),
            ("Format Document", [], ["clean up the indentation in this file", "make this code consistently spaced"]),
            ("Split Editor", [], ["i want two files open next to each other in here", "show the test file beside the source"]),
            ("Go to Definition", [], ["where is this function actually written", "jump to where this class is declared"]),
            ("Problems", [], ["show me all the errors and warnings", "what's the compiler complaining about"]),
            ("Command Palette", [], ["let me type in any editor command", "open that box where i can search every action"]),
            ("Pull", [], ["get my teammates' latest changes", "sync down what's on the remote branch"]),
            ("Toggle Breakpoint", [], ["stop execution on this line", "pause right here when it runs"]),
            ("Find in Files", [], ["search the whole project for this config key", "where else is this variable used across the repo"]),
        ],
    },
    {
        "app": "Code review page",
        "elements": [
            ("tab", "Files Changed", ""), ("tab", "Checks", ""), ("tab", "Conversation", ""), ("button", "Re-run Jobs", ""),
            ("button", "Request Changes", ""), ("button", "Approve", ""), ("button", "Reviewers", "Request review"),
            ("button", "Convert to Draft", ""), ("button", "Copy Branch Name", ""), ("button", "Resolve Conversation", ""),
            ("button", "Labels", ""), ("button", "Merge", ""), ("button", "Close", ""),
        ],
        "goals": [
            ("Files Changed", [], ["show me the actual code diff", "i want to read the changes line by line"]),
            ("Checks", [], ["why did ci fail on this", "see which test job went red"]),
            ("Re-run Jobs", [], ["the tests were flaky, kick them off again", "try the pipeline one more time"]),
            ("Request Changes", [], ["this isn't ready, block it until they fix the null check", "formally ask for revisions on this"]),
            ("Approve", [], ["looks good to me, sign off on it", "give this my green light"]),
            ("Reviewers", [], ["get marcus to look at this too", "ask the security team to review"]),
            ("Convert to Draft", [], ["mark this as not ready for review yet", "take this back to work in progress"]),
            ("Copy Branch Name", [], ["i need the branch name to check it out locally", "grab the branch so i can pull it"]),
            ("Resolve Conversation", [], ["that comment's been addressed, close it out", "mark this discussion as handled"]),
            ("Labels", [], ["tag this as a bug fix", "categorize this pr as documentation"]),
            ("Conversation", [], ["show me the discussion and comments", "what have people said about this so far"]),
        ],
    },
    {
        "app": "Task manager",
        "elements": [
            ("button", "Deadline", ""), ("button", "Repeat", ""), ("button", "Checklist", "Add checklist"), ("button", "Someday", ""),
            ("button", "Logbook", "Completed items"), ("button", "Tags", ""), ("button", "When", "Schedule"), ("button", "Today", ""),
            ("button", "Quick Find", ""), ("button", "Move to Project", ""), ("button", "Delete To-Do", ""),
        ],
        "goals": [
            ("Deadline", [], ["this has to be finished by friday, set that", "make sure it shows as due on the 30th"]),
            ("Repeat", [], ["i do this every monday, make it recur", "have this task come back each month"]),
            ("Checklist", [], ["break this task into smaller steps", "add sub-items under this one"]),
            ("Someday", [], ["i'll do this eventually, no rush", "park this idea with no date"]),
            ("Logbook", [], ["show me what i already finished", "what did i complete last week"]),
            ("Tags", [], ["label this as an errand", "mark this one as needing the car"]),
            ("When", [], ["push this to tomorrow", "i'll start this on saturday"]),
            ("Today", [], ["show only what i need to do today", "what's on my plate for the day"]),
            ("Move to Project", [], ["this belongs in the kitchen remodel project", "file this task under work"]),
        ],
    },
    {
        "app": "Video call (in meeting)",
        "elements": [
            ("button", "Raise Hand", ""), ("button", "Share Screen", ""), ("button", "Stop Video", ""), ("button", "Mute Microphone", ""),
            ("button", "Background", "Virtual background and blur"), ("button", "Record", ""), ("button", "Participants", ""),
            ("button", "Chat", ""), ("button", "Gallery View", ""), ("button", "Reactions", ""), ("button", "Leave", ""),
            ("button", "Live Captions", ""),
        ],
        "goals": [
            ("Raise Hand", [], ["i have a question, let the host know", "signal that i want to speak next"]),
            ("Share Screen", [], ["let everyone see my slides", "show them what's on my monitor"]),
            ("Stop Video", [], ["i don't want them to see me right now", "turn my camera off"]),
            ("Mute Microphone", [], ["my dog is barking, cut my audio", "they can hear my keyboard, stop sending my sound"]),
            ("Background", [], ["blur my messy room behind me", "put a fake office behind me"]),
            ("Record", [], ["capture this meeting so i can rewatch it", "keep a recording of this call"]),
            ("Participants", [], ["admit the people in the waiting room", "show the attendee list so i can rename myself"]),
            ("Chat", [], ["drop a link in the text sidebar for everyone", "type a message to the whole meeting"]),
            ("Gallery View", [], ["show everyone's faces at once", "i want to see all the attendees in a grid"]),
            ("Reactions", [], ["send a clapping emoji to the speaker", "throw up a quick thumbs up on screen"]),
            ("Live Captions", [], ["show what people are saying as text", "the audio is choppy, turn on transcription"]),
        ],
    },
    {
        "app": "Flight booking results",
        "elements": [
            ("button", "Price Alerts", "Track prices"), ("button", "Flexible Dates", ""), ("button", "Seat Map", ""), ("button", "Add Bags", ""),
            ("button", "Change Flight", ""), ("button", "Filters", ""), ("button", "Book", ""), ("link", "Baggage Policy", ""),
            ("button", "Fare Details", "What's included"), ("button", "Add to Calendar", ""),
        ],
        "goals": [
            ("Price Alerts", [], ["tell me if this fare drops", "watch this route and email me if it gets cheaper"]),
            ("Flexible Dates", [], ["show me cheaper days around this weekend", "i can leave a day earlier if it saves money"]),
            ("Seat Map", [], ["i want a window seat", "pick where i'm sitting on the plane"]),
            ("Add Bags", [], ["i'm checking a suitcase", "i'll have two big bags with me"]),
            ("Change Flight", [], ["i need to move to a later departure", "switch me to the morning flight instead"]),
            ("Baggage Policy", [], ["how heavy can my carry-on be", "what are the luggage rules on this airline"]),
            ("Fare Details", [], ["does this ticket include a meal and refunds", "what do i actually get with this fare"]),
            ("Add to Calendar", [], ["put this trip on my schedule", "block my calendar for the flight times"]),
        ],
    },
    {
        "app": "Podcast player",
        "elements": [
            ("button", "Follow", ""), ("button", "Download Episode", ""), ("button", "Skip Forward 30", ""), ("button", "Rewind 15", ""),
            ("button", "Speed", ""), ("button", "Episode Notes", ""), ("button", "Up Next", ""), ("button", "Mark as Played", ""),
            ("button", "Sleep Timer", ""), ("button", "Share Episode", ""), ("button", "Remove Download", ""),
        ],
        "goals": [
            ("Skip Forward 30", [], ["jump past this ad read", "this sponsor bit is boring, move ahead a bit"]),
            ("Rewind 15", [], ["i missed what she just said, go back a little", "replay the last few seconds"]),
            ("Episode Notes", [], ["what were the links they mentioned in this one", "show the show notes and guest info"]),
            ("Mark as Played", [], ["i already heard this one", "clear this episode from my unplayed list"]),
            ("Follow", [], ["get new episodes of this show automatically", "add this show to my library"]),
            ("Download Episode", [], ["save this for the subway where i have no signal", "keep this episode on the device"]),
            ("Speed", [], ["make the hosts talk faster", "listen at 1.5x"]),
            ("Up Next", [], ["what's lined up after this episode", "show my listening queue"]),
            ("Sleep Timer", [], ["stop playing after twenty minutes, i'm dozing off", "end playback at the end of this episode"]),
        ],
    },
    {
        "app": "Finder window",
        "elements": [
            ("button", "Quick Look", ""), ("button", "Get Info", ""), ("button", "Compress", ""), ("button", "AirDrop", ""),
            ("button", "Eject", ""), ("button", "View as List", ""), ("button", "New Folder", ""), ("button", "Tags", ""),
            ("button", "Group By", ""), ("button", "Move to Trash", ""), ("button", "Show Path", ""),
        ],
        "goals": [
            ("Quick Look", [], ["peek at this file without opening an app", "preview what's in this pdf real quick"]),
            ("Get Info", [], ["how big is this file and when was it made", "see this file's size and permissions"]),
            ("Compress", [], ["make this folder into a zip", "squash these so they're small enough to email"]),
            ("AirDrop", [], ["beam this to my phone sitting right here", "get this picture onto my partner's iphone next to me"]),
            ("Eject", [], ["i'm done with the usb stick, make it safe to pull out", "unmount the external drive"]),
            ("View as List", [], ["show the files as rows with dates", "i want columns for size and modified date"]),
            ("New Folder", [], ["i need a place to group these files together", "make a container for the tax documents"]),
            ("Group By", [], ["cluster these by file type", "organize the window by kind"]),
            ("Show Path", [], ["where on disk does this live", "show the full location of this folder"]),
        ],
    },
    {
        "app": "Social feed post",
        "elements": [
            ("button", "Repost", ""), ("button", "Quote", "Quote post"), ("button", "Not Interested", "See fewer posts like this"),
            ("button", "Mute Account", ""), ("button", "Post Notifications", "Turn on notifications for this account"),
            ("button", "Replies", "Show replies"), ("button", "Save Post", ""), ("button", "Translate Post", ""), ("button", "Follow", ""),
            ("button", "Block", ""), ("button", "Copy Post Link", ""),
        ],
        "goals": [
            ("Repost", [], ["spread this to my followers as is", "boost this to my timeline unchanged"]),
            ("Quote", [], ["share this with my own comment on top", "add my take and repost it"]),
            ("Not Interested", [], ["i keep seeing this kind of stuff, show me less", "the algorithm needs to stop pushing these at me"]),
            ("Mute Account", [], ["i don't want to see this person anymore but don't unfollow", "quietly hide this guy from my feed"]),
            ("Post Notifications", [], ["ping me whenever this account posts", "never miss an update from them"]),
            ("Replies", [], ["what are people saying in response", "open the comment thread under this"]),
            ("Translate Post", [], ["this post is in korean, what does it say in english", "convert this caption to english"]),
            ("Follow", [], ["i want this person's stuff in my feed", "start following this writer"]),
        ],
    },
    {
        "app": "E-book reader",
        "elements": [
            ("button", "Look Up", "Dictionary"), ("button", "Font Size", "Aa"), ("button", "Contents", "Table of contents"),
            ("button", "Mark Page", ""), ("button", "Night Mode", ""), ("button", "Search Book", ""), ("button", "Highlight", ""),
            ("button", "My Notes", ""), ("button", "Go to Page", ""), ("button", "Read Aloud", ""),
        ],
        "goals": [
            ("Look Up", [], ["what does this word mean", "define the word under my cursor"]),
            ("Font Size", [], ["the letters are too small to read comfortably", "make the type bigger in this book"]),
            ("Contents", [], ["jump to chapter seven", "show me the list of chapters"]),
            ("Mark Page", [], ["remember where i stopped reading", "hold my place here"]),
            ("Night Mode", [], ["make the page dark so it doesn't hurt my eyes in bed", "switch to white text on black"]),
            ("Search Book", [], ["where did the captain first appear in this book", "find every mention of the lighthouse"]),
            ("Highlight", [], ["color this sentence yellow so it stands out when i reread", "mark this quote in the text"]),
            ("My Notes", [], ["show everything i've annotated in this book", "see my margin comments"]),
            ("Read Aloud", [], ["read this chapter to me", "i want to listen instead of reading"]),
        ],
    },
]

# Goal → app, for dock-icon screens ("open the app that …" without naming it).
# (target_app, alternate_apps, phrasings). Distractor apps come from DOCK_APP_POOL minus target/alternates.
APP_PURPOSE_GOALS = [
    ("iMovie", ["Final Cut Pro"], ["i want to cut together a video of our trip"]),
    ("iMovie", [], ["stitch these phone clips into a little movie with music"]),
    ("GarageBand", ["Logic Pro"], ["record a song with my guitar"]),
    ("GarageBand", [], ["mess around with some drum loops for fun"]),
    ("Calculator", [], ["i need to do some quick arithmetic", "what's 18 percent of 240, open something to work it out"]),
    ("Terminal", ["iTerm"], ["i need to run a shell command"]),
    ("Terminal", [], ["ssh into the build server"]),
    ("Preview", [], ["sign this pdf someone sent me", "look at this scanned receipt"]),
    ("Maps", [], ["figure out how far the airport is", "see the route to the stadium"]),
    ("Photos", [], ["look through my vacation pictures", "find the picture from the wedding"]),
    ("FaceTime", ["WhatsApp"], ["video chat with my parents"]),
    ("FaceTime", [], ["start an apple video call with my sister's iphone"]),
    ("Contacts", [], ["find priya's phone number", "update my dentist's address"]),
    ("Voice Memos", [], ["record a quick audio note to myself", "capture this lecture as audio"]),
    ("App Store", [], ["get a new app", "download that game everyone's playing"]),
    ("Activity Monitor", [], ["see what's eating my cpu", "something is making the fans spin, find the culprit"]),
    ("Books", [], ["continue the novel i was reading", "pick up my audiobook where i left off"]),
    ("1Password", [], ["look up my streaming password", "find the wifi password i saved"]),
    ("Microsoft Word", [], ["write up my resume", "draft a formal report in a word processor"]),
    ("PowerPoint", [], ["build slides for monday's pitch", "make a slideshow for the class"]),
    ("Blender", [], ["make a 3d model of a chair", "render a spinning logo in 3d"]),
    ("Postman", [], ["test our api endpoint", "fire a request at the staging server"]),
    ("Docker", [], ["start my local containers", "spin up the database container"]),
    ("TablePlus", [], ["poke around in the production database", "run a sql query against staging"]),
    ("Obsidian", [], ["add to my personal knowledge base", "link this idea into my second brain"]),
    ("Linear", [], ["file a bug ticket for the team", "check the sprint board"]),
    ("WhatsApp", ["Telegram"], ["message my family group chat"]),
    ("Discord", [], ["hang out with my gaming friends", "join the voice channel for tonight's raid"]),
    ("Chrome", ["Firefox"], ["browse the web"]),
    ("Weather", [], ["see if i need an umbrella tomorrow", "check the forecast for the weekend"]),
    ("Podcasts", [], ["catch up on the shows i subscribe to", "find a new true crime show to listen to"]),
    ("TV", [], ["watch the next episode of my show", "rent a movie for tonight"]),
    ("Clock", [], ["check what time it is in tokyo", "see the world clocks"]),
    ("Stocks", [], ["see how the market's doing today", "check my watchlist tickers"]),
    ("Font Book", [], ["install the typeface i downloaded", "preview the fonts on this mac"]),
    ("Photo Booth", [], ["take a silly selfie with the webcam", "snap a quick picture of myself"]),
]
DOCK_APP_POOL = sorted({app for app, alternates, _ in APP_PURPOSE_GOALS for app in [app, *alternates]})

# Attribute picks: a list of same-kind items, the request asks for an extreme of one attribute.
# Each domain: row labels, attribute value ranges (integers), a text template whose placeholders the generator
# renders with units (ATTRIBUTE_DISPLAY_FORMATTERS there), and goal phrasings keyed by (attribute, min|max).
ATTRIBUTE_PICK_DOMAINS = [
    {
        "domain": "flights", "role": "row",
        "labels": ["UA 214", "DL 88", "AA 1201", "B6 615", "AS 330", "WN 2207", "NK 940"],
        "attributes": {"price": (89, 640), "duration_minutes": (300, 720), "departure_hour": (5, 22), "stops": (0, 2)},
        "text": "{price} · {duration_minutes} · departs {departure_hour} · {stops}",
        "asks": {
            ("price", "min"): ["go with whichever flight costs the least", "i'm on a budget, grab the lowest fare", "the one that's easiest on my wallet"],
            ("duration_minutes", "min"): ["which flight gets me there quickest, pick that", "i want the shortest time in the air"],
            ("departure_hour", "min"): ["i want to leave as early in the day as possible", "the first departure of the day please"],
            ("departure_hour", "max"): ["give me the one that leaves latest, i work till evening"],
            ("stops", "min"): ["i hate layovers, pick the one with the fewest stops"],
        },
    },
    {
        "domain": "laptops", "role": "row",
        "labels": ["Aero 13", "Strata 14", "Volt Pro 16", "Nimbus Air", "Ridge 15", "Quill X1"],
        "attributes": {"price": (699, 2899), "weight_pounds_tenths": (24, 55), "battery_hours": (6, 22)},
        "text": "{price} · {weight_pounds_tenths} · {battery_hours} battery",
        "asks": {
            ("weight_pounds_tenths", "min"): ["i carry it everywhere, choose the lightest one", "whichever is easiest to lug around"],
            ("battery_hours", "max"): ["i need the one that lasts longest unplugged", "pick the laptop with the best battery life"],
            ("price", "max"): ["money's no object, show me the top-end one"],
        },
    },
    {
        "domain": "apartments", "role": "row",
        "labels": ["2BR on Elm St", "Loft on 5th", "Studio by the Park", "1BR Harbor View", "3BR Maple Ave", "Garden Unit on Oak"],
        "attributes": {"rent": (1400, 4200), "square_feet": (420, 1600), "minutes_to_train": (2, 25)},
        "text": "{rent}/mo · {square_feet} · {minutes_to_train} walk to train",
        "asks": {
            ("square_feet", "max"): ["we need space, open the biggest place", "which listing has the most room, that one"],
            ("minutes_to_train", "min"): ["i commute daily, pick the one nearest the station", "the apartment with the shortest walk to the train"],
            ("rent", "min"): ["open the listing with the lowest monthly rent"],
        },
    },
    {
        "domain": "recipes", "role": "row",
        "labels": ["Lemon Garlic Pasta", "Sheet Pan Chicken", "Black Bean Tacos", "Miso Salmon", "Veggie Curry", "Shakshuka"],
        "attributes": {"minutes": (12, 75), "rating_tenths": (38, 49), "calories": (320, 910)},
        "text": "{minutes} · {rating_tenths} · {calories}",
        "asks": {
            ("minutes", "min"): ["i'm starving, which one can i make fastest", "open the recipe that takes the least time"],
            ("calories", "min"): ["i'm watching my calories, pick the lightest dish"],
            ("rating_tenths", "max"): ["go with the one people liked best"],
        },
    },
    {
        "domain": "restaurants", "role": "row",
        "labels": ["Nori House", "Casa Lupe", "The Copper Pot", "Pho Saigon", "Bella Napoli", "Smoke & Ash BBQ"],
        "attributes": {"distance_tenths_miles": (2, 60), "review_tenths": (35, 49), "closing_hour": (20, 24)},
        "text": "{distance_tenths_miles} · {review_tenths} · open until {closing_hour}",
        "asks": {
            ("distance_tenths_miles", "min"): ["i don't want to walk far, pick the nearest one", "whichever spot is closest to me"],
            ("closing_hour", "max"): ["it's getting late, which place stays open the longest", "pick the restaurant that closes last"],
            ("review_tenths", "max"): ["take me to the best reviewed spot"],
        },
    },
    {
        "domain": "files", "role": "row",
        "labels": ["export_q1.csv", "site-backup.tar", "demo-recording.mov", "brand-assets.zip", "notes-archive.md", "raw-photos.dng"],
        "attributes": {"megabytes": (2, 9000), "days_since_modified": (0, 400)},
        "text": "{megabytes} · modified {days_since_modified}",
        "asks": {
            ("megabytes", "max"): ["which of these is hogging the most space, select it", "click the biggest file"],
            ("days_since_modified", "min"): ["select whatever i touched most recently", "the file i edited last, pick that"],
        },
    },
    {
        "domain": "support tickets", "role": "row",
        "labels": ["#4410 login loop", "#4418 invoice wrong", "#4421 app crash", "#4425 slow export", "#4430 sso error"],
        "attributes": {"hours_waiting": (1, 96), "customers_affected": (1, 400)},
        "text": "waiting {hours_waiting} · {customers_affected} customers",
        "asks": {
            ("hours_waiting", "max"): ["open the ticket that's been waiting the longest", "who has been stuck in the queue longest, that one"],
            ("customers_affected", "max"): ["pick the issue hitting the most customers"],
        },
    },
    {
        "domain": "headphones", "role": "row",
        "labels": ["Arc ANC", "Pulse Buds", "Halo Studio", "Drift Sport", "Echo Lite"],
        "attributes": {"price": (39, 449), "review_count": (12, 9800), "battery_hours": (5, 60)},
        "text": "{price} · {review_count} reviews · {battery_hours} battery",
        "asks": {
            ("review_count", "max"): ["the pair with the most reviews, open that one", "which one have the most people bought and reviewed"],
            ("battery_hours", "max"): ["i fly a lot, choose the ones with the longest battery"],
            ("price", "min"): ["just the budget pair, the least expensive"],
        },
    },
]

# Contrast set: goals that two or more elements on the SAME screen genuinely satisfy, so the right
# next step is ASK_USER. (app context as in APP_SCREEN_CONTEXTS, fitting labels, phrasings.)
# These teach the boundary: "goal maps to exactly one element → click; to several → ask".
AMBIGUOUS_GOALS = [
    ("Mail (reading a message)", ["Flag", "Snooze", "Mark as Unread"], ["don't let this one slip, i'll handle it later", "i can't answer this now, keep it on my radar"]),
    ("Mail (reading a message)", ["Archive", "Move"], ["get this out of my inbox and put it somewhere else"]),
    ("Mail (reading a message)", ["Move to Junk", "Unsubscribe", "Block Sender"], ["i'm sick of getting these, make it stop"]),
    ("Mail (composing)", ["Attach", "Add Image"], ["put the photo in this email"]),
    ("Mail (composing)", ["Cc", "Bcc"], ["include my manager on this one", "add legal to this message too"]),
    ("Web browser toolbar", ["Zoom In", "Reader View"], ["this page is really hard to read"]),
    ("Web browser toolbar", ["History", "Previous Page"], ["get me back to the site i was just on"]),
    ("Shopping product page", ["Compare", "See Similar"], ["show me how this compares to other options"]),
    ("Shopping product page", ["Questions & Answers", "Chat with Seller"], ["i have a question about whether this fits a queen bed"]),
    ("Video player", ["Full Screen", "Theater Mode"], ["make the video bigger", "i want a larger picture"]),
    ("Video player", ["Thumbs Up", "Subscribe"], ["i want to support this creator"]),
    ("Music app (now playing)", ["Heart", "Add to Playlist"], ["keep this song, i love it"]),
    ("Music app (now playing)", ["Go to Artist", "Song Radio"], ["i want more music from whoever this is"]),
    ("Team chat channel", ["Reply in Thread", "Add Reaction"], ["acknowledge her message"]),
    ("Team chat channel", ["Do Not Disturb", "Set Status"], ["let people know not to bother me right now"]),
    ("Document editor", ["Comment", "Suggesting"], ["give feedback on this paragraph", "mark up this section for the author"]),
    ("Document editor", ["Export PDF", "Share Doc"], ["get this document over to my professor"]),
    ("Spreadsheet", ["AutoSum", "Pivot Table"], ["total up the sales for me"]),
    ("Spreadsheet", ["Sort", "Filter"], ["organize this so the march rows are easy to find"]),
    ("System Settings", ["Bluetooth", "Sound"], ["my wireless earbuds aren't playing any audio"]),
    ("System Settings", ["Displays", "Accessibility"], ["make everything on screen bigger"]),
    ("System Settings", ["Lock Screen", "Privacy & Security"], ["make my mac more secure"]),
    ("Maps place card", ["Call", "Website"], ["find out if they're open right now"]),
    ("Maps place card", ["Look Around", "Satellite"], ["show me what this place looks like"]),
    ("Calendar event details", ["Accept", "Maybe"], ["respond to this invite"]),
    ("Calendar event details", ["Propose New Time", "Edit Event"], ["move this meeting an hour later"]),
    ("Photo editor", ["Auto-Enhance", "Light"], ["this photo is too dark, fix it"]),
    ("Photo editor", ["Crop", "Straighten"], ["the framing is off on this one"]),
    ("Food delivery order", ["Contact Driver", "Delivery Instructions"], ["the driver needs to know the gate code"]),
    ("Food delivery order", ["Track Order", "Contact Driver"], ["where is my driver"]),
    ("Code editor", ["Problems", "Terminal"], ["show me the build errors"]),
    ("Code editor", ["Find in Files", "Go to Definition"], ["find this function in the codebase"]),
    ("Code review page", ["Approve", "Request Changes"], ["submit my review on this"]),
    ("Code review page", ["Files Changed", "Conversation"], ["see the review comments on the code"]),
    ("Task manager", ["When", "Deadline"], ["this needs to happen by thursday"]),
    ("Task manager", ["Someday", "When"], ["i'll do this one later"]),
    ("Video call (in meeting)", ["Stop Video", "Background"], ["i don't want them to see my messy room"]),
    ("Video call (in meeting)", ["Chat", "Reactions"], ["tell the speaker i agree without unmuting"]),
    ("Flight booking results", ["Change Flight", "Flexible Dates"], ["i need to fly a day later"]),
    ("Flight booking results", ["Baggage Policy", "Fare Details"], ["can i bring a carry-on with this ticket"]),
    ("Podcast player", ["Skip Forward 30", "Speed"], ["get through this episode faster"]),
    ("Podcast player", ["Mark as Played", "Remove Download"], ["i'm finished with this episode"]),
    ("Finder window", ["Quick Look", "Get Info"], ["tell me about this file before i open it"]),
    ("Finder window", ["View as List", "Group By"], ["organize this window so it's easier to scan"]),
    ("Social feed post", ["Not Interested", "Mute Account"], ["i don't want to see posts like this guy's"]),
    ("Social feed post", ["Repost", "Quote"], ["share this with my followers"]),
    ("E-book reader", ["Font Size", "Night Mode"], ["this is hard on my eyes"]),
    ("E-book reader", ["Contents", "Go to Page"], ["skip ahead to the second half of the book"]),
]
